version: '3.1'

services:
  sdp_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=sdp
      - PGDATA=/var/lib/postgresql/data/pgdata
    container_name: sdp_db
    ports:
      - 5432:5432
    volumes:
    - ./database/volume/dbx:/var/lib/postgresql/data

  sdp_backend:
    image: kylecotton/sdp_backend:latest
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - DATABASE_URL=postgres://postgres:password@sdp_db/sdp
    container_name: sdp_backend
    volumes:
      - ./sdp-backend/static:/usr/src/sdp-backend/static
