version: '3.1'

services:
  sdp_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=sdp
      - PGDATA=/var/lib/postgresql/data/pgdata
    container_name: sdp_db
    ports:
      - 5432:5432
    volumes:
    - ./volume/dbx:/var/lib/postgresql/data
